apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bill-dev-vcluster-cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: bill-dev-vcluster
  source:
    repoURL: git@github.com:mrsimonemmsorg/gitops.git
    path: registry/clusters/bill-dev-vcluster/cluster-secret-store
    targetRevision: HEAD
  destination:
    name: bill-dev-vcluster
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
